spring.datasource.url=jdbc:mysql://mysql-17b9917f-jainshaman09-70aa.c.aivencloud.com:12978/defaultdb?ssl-mode=REQUIRED&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_a8XeSZauvqI2iFZdDHl
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.application.name=hms-backend
server.port=8080

app.jwt.secret=hms_secret_key_hospital_management_2024_secure
app.jwt.expiration=86400000